cart/urls.py
from django.urls import path,re_path

from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<id>\d+)/$', views.cart_add, name='cart_add'),
]

pc/urls.py
from django.contrib import admin
from django.urls.conf import path, include
from django.conf import settings
from django.conf.urls.static import static
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', index,name='glavn'),
    path('katalog/', katalog,name='kstslog'),
    path('katalog/<int:id>/', kateg, name='tovar'),
    path('katalog-filter/<int:stat_id>/',filter,name='stat'),
    path('katalog-inform-tovar/<int:pk>/',inform,name='inform'),
    path('new',new),
    path('poisk',sarch,name='search'),
    path('reg',reg,name='reg'),
    path('prof',prof,name='profile'),
    path('login/',LoginUser.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('about_us/',about,name='us'),
    path('politik/',politik,name='polit'),
    path('servis/',servis,name='servis'),
    path('social/',social,name='social')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/about_us.html
{% extends 'index.html' %}

{% block main %}
<div class="main_about">
    <h1>О нас</h1>
    <p> PC- это ваш надежный источник качественных компьютерных комплектующих и периферии</p>
    <h3>Наша миссия:</h3>
    <p>  Предоставить нашим клиентам широкий выбор комплектующих от ведущих мировых производителей.</p>
    <p>Гарантировать высокое качество товаров и доступные цены.</p>
    <p>Обеспечить клиентам безупречный сервис и профессиональную консультацию.</p>
    <h3>Что отличает нас от других:</h3>
    <p>Обширный ассортимент: У нас вы найдете все, что нужно для сборки персонального компьютера или модернизации уже имеющегося.</p>
    <p>Высокое качество: Мы сотрудничаем только с проверенными поставщиками, поэтому гарантируем качество всех наших товаров.</p>
    <p>Конкурентоспособные цены: Мы предлагаем конкурентные цены на все товары, чтобы сделать покупку максимально выгодной для вас.</p>
    <p>Индивидуальный подход: Наши опытные консультанты всегда готовы помочь вам с выбором комплектующих, подобрать оптимальную конфигурацию и ответить на любые ваши вопросы.</p>
    <p>Быстрая доставка: Мы предлагаем различные варианты доставки, чтобы вы получили свой заказ максимально быстро и удобно.</p>
    <p>Гарантия качества: Мы предоставляем гарантию на все товары в соответствии с условиями производителя.</p>
    <h3>Наши ценности:</h3>
    <p>Клиент на первом месте: Мы стремимся к тому, чтобы каждый клиент был доволен покупкой и возвращался к нам снова.</p>
    <p>Профессионализм: Мы всегда работаем на высоком уровне, стараясь соответствовать всем вашим ожиданиям.</p>
    <p>Доверие: Мы ценим доверие наших клиентов и стараемся его оправдывать.</p>
    <h3>Присоединяйтесь к нам:</h3>
    <p>Подпишитесь на наши социальные сети.</p>
</div>
{% endblock %}

app/templates/filter.html
{% extends 'index.html' %}
{% block main %}
<div class="main_vivod">
    {%for i in tovar%}
    <div class="tovars">
        <div class="tv_img">
            <img src="{{i.img.url}}" alt="" class="tovar_img">
        </div>
        <div class="tv_text">
            <h3>{{i.comp}} <a href="{{i.get_absolute_url}}">{{i.name}}</a></h3>
            <h2 class="price">{{i.price}}</h2>
            <form action="{% url 'cart:cart_add' pk %}" method="post">
                     {% csrf_token %}
                     <input type="submit" value="Добавить в корзину" class="cart">
                 </form>
        </div>
    </div>
    {%endfor%}

    </div>
{% endblock %}

app/templates/index.html
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/slick-1.8.1/slick/slick-theme.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/slick-1.8.1/slick/slick.css'%}">

    <title>Document</title>
</head>
<body>
<header>
        <div class="header">
            <div class="logo">
                <img src="{% static 'images./lg.png'%}" alt="" class="lg">
                <div class="wrapper" id="bur">
                <button class="nav">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
    </div>
            </div>
            <div class="menu" id="menu">
                <ul>
                    <a href="/" class="menu_a"><li>Главная</li></a>
                    <a href="/new" class="menu_a"><li>Новости</li></a>
                    <a href="#" class="menu_a"><li id="but_sap">Поддержка</li></a>
                    <div class="wind">
                    <a href="/katalog"class="menu_a"><li id="katalog">Каталог</li></a>
                    <div class="katalog" id="win_kat">
                        <div class="katalogs">
                        {%for i in kateg%}
                        <a href="katalog/{{i.id}}" class="win_a">{{i.name}}</a>
                            {%endfor%}
                        </div>
                    <div class="cpu" id="categories">
                        {%for c in stat.all%}
                        <a href="/katalog-filter/{{c.id}}" class="win_a">{{c.name}}</a>
                        {%endfor%}
                    </div>
                    </div>
                    </div>
                </ul>
            </div>
            <div class="forma" id="poisk">
                <div class="poisk" >
                    <form class="search-bar" action="{% url 'search' %}">
                        <input class="search-inp" type="text" placeholder="Поиск" name="query"/>
                        <button class="search-btn" type="submit"><img class="but" src="{% static 'images./lup.png'%}"></button>
                    </form>
                </div>
            </div>
            <div class="user_and_basket" id="reg">
                {% if user.is_authenticated %}
            	<a class="nav-item nav-link" href="{% url 'profile' %}">Профиль</a>
          	    {% else %}
            	<a class="nav-item nav-link" href="{% url 'login' %}">Вход/</a>
            	<a class="nav-item nav-link" href="{% url 'reg' %}">Регистрация</a>
          	    {% endif %}
                <a href="{% url 'reg' %}"><img src="{% static 'images./user.png'%}" class="user"></a>

                <a href="/cart"><img src="{% static 'images./kar.png'%}" class="kar" ></a>

            </div>

        </div>

</header>
<div class="main">
    <div class="sap_wind" id="sap">
        <p id="sub">Окно поддержки</p>
        <form method="post">
    {% csrf_token %}
            <input type="text" placeholder="Ваше имя" name="name">
            <input type="text" placeholder="Почта" name="email">
            <input type="text" placeholder="Вопрос" name="message">
    <button type="submit">Отправить</button>
</form>
    </div>

    {% block main %}
    <img src="{% static 'images./fon.png'%}" alt="" class="fon">
    <div class="slide">
        <div class="sli">
            {%for i in kateg%}
        <div class="block1">
          <img src="{{i.img.url}}">
            <a  href="katalog/{{i.id}}" id="wind_p">{{i.name}}</a>
        </div>
            {%endfor %}

    </div>
    </div>

    <div class="tv">
    {%for i in tovar%}
    <div class="tovars">
        <div class="tv_img">

            <img src="{{i.img.url}}" alt="" class="tovar_img">

        </div>
        <div class="tv_text">
            <h3>{{i.amre}} <a href="{{i.get_absolute_url}}">{{i.name}}</a></h3>
            <h2 class="price">{{i.price}}</h2>
        </div>
    </div>
    {%endfor%}
        </div>
    {% endblock %}
</div>

<footer>
    <div class="footer">
    <<div class="row">
<a href="#"><i class="fa fa-facebook"></i></a>
<a href="#"><i class="fa fa-instagram"></i></a>
<a href="#"><i class="fa fa-youtube"></i></a>
<a href="#"><i class="fa fa-twitter"></i></a>
</div>

<div class="row">
<ul>
<li><a href="{% url 'us' %}">О Нас</a></li>
<a><li id="but_sap1">Помощь</li></a>
<li><a href="{%url 'social'%}">Наши сервисы</a></li>
<li><a href="{% url 'servis' %}">Где находится наш сервис</a></li>
<li><a href="{%url  'polit' %}">Политика конфиденциальности </a></li>
</ul>
</div>
django-admin startproject PC
<div class="row">
 © 2024
</div>
</div>
</footer>
</body>
<script src="{% static 'js/jquery-3.7.0.min.js'%}"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="{% static 'js/slick-1.8.1/slick/slick.js'%}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'js/js.js'%}"></script>
</html>

app/templates/inf.html
{% extends 'index.html' %}

{% block main %}

<div class="main2">
    {%for i in tovar%}

    <div class="tv_vivod">
        <h1>{{i.comp}} {{i.name}}</h1>
        <div class="cont">
            <img src="{{i.img.url}}" alt="" class="tovar_img">

        <div class="text_vivod">
            <div class="a">
            <p>Производитель</p>
            {%for a in i.pod_kat.all%}
                <p class="e">{{a.name}}</p>
            {%endfor%}
            <p>{{i.price}} ₽</p>

                 <form action="{% url 'cart:cart_add' pk %}" method="post">
                     {% csrf_token %}
                     <input type="submit" value="Добавить в корзину" class="cart">
                 </form>

            </div>
            <div class="stat">
                <p>{{i.comp}}</p>
                {%for a in i.pod_kat.all%}
                    {%for b in a.stat.all%}
                        <p>{{b.name}}</p>
                    {%endfor%}
                {%endfor%}
            </div>

        </div>

        </div>
    </div>
    {%endfor%}
    </div>

{% if user.is_authenticated %}
<form method="post" name="modal2" class="form2" id="form1" action="{% url 'inform' pk %}">
        {%csrf_token%}
            <div class="namesur">
                <div class="rating-area">
	            <input type="radio" id="star-5" name="rating" value="5">
	            <label for="star-5" title="Оценка «5»"></label>
	            <input type="radio" id="star-4" name="rating" value="4">
	            <label for="star-4" title="Оценка «4»"></label>
	            <input type="radio" id="star-3" name="rating" value="3">
	            <label for="star-3" title="Оценка «3»"></label>
	            <input type="radio" id="star-2" name="rating" value="2">
	            <label for="star-2" title="Оценка «2»"></label>
	            <input type="radio" id="star-1" name="rating" value="1">
	            <label for="star-1" title="Оценка «1»"></label>
         </div>
                <input name="content" type="text" class="in2" placeholder="Введите комментарий">
            </div>


        <button class="koment" id="loadMore">Сохранить</button>
    </form>
{% else %}
<div class="not_com">
    <p>Пожайлуста <a href="{% url 'reg' %}" class="a_com">Регистрация/</a><a href="{%url 'login'%}" class="a_com">Войти</a> Пожалуйста, войдите или зарегистрируйтесь, чтобы написать отзыв</p>
    </div>
{% endif %}

{% for comment in tov.reviews.all %}
<div class="otz" id="reviews">
    <div class="pust"></div>
    <img src="{{ comment.user.profile.image.url  }}" alt="" class="def">
    <div class="name_com"><div class="name"><p>{{ comment.user }}</p> <p>Оценка:{{comment.rating}}</p></div> <div class="coment">Коментарий:{{ comment.content }}</div></div>
    </div>
    <div class="pust2"></div>
    {% endfor %}

{% endblock %}

app/templates/katalog.html
{% extends 'index.html' %}
{% block main %}
<div class="main_katal">
<div class="kontent">
    {%for i in kateg%}
 <div class="block2">
     <img src="{{i.img.url}}" class="katal">
      <a href="{{i.id}}" id="a_kat">{{i.name}}</a>
 </div>
     {%endfor %}
</div>
    </div>
{% endblock %}

app/templates/login.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block main %}
<div class="main_log">
<div class="content-section">
        <form method="POST" class="form5">
        {% csrf_token %}
        <label aria-hidden="true" id="auth">Аутентификация</label>
        <input type="text" id="user" name="username" required placeholder="Имя пользователя">
        <input type="password" id="password" name="password" required placeholder="Пароль">
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Войти</button>
        </div>
        </form>

    </div>
    </div>
{% endblock %}

app/templates/new.html
{% extends 'index.html' %}
{% block main %}
<div class="new">
    {%for i in new%}
    <img src="{{i.img.url}}" alt="">
    <div class="stat_new">
    <p>Дата статьи {{i.data}}</p>
    {{i.text}}
        </div>
    {%endfor%}
</div>
{% endblock %}

app/templates/poisk.html
{% extends 'index.html' %}
{% block main %}
<div class="main_vivod">
{%for i in tovar%}
    <div class="tovars">
        <div class="tv_img">

            <img src="{{i.img.url}}" alt="" class="tovar_img">

        </div>
        <div class="tv_text">
            <h3>{{i.comp}} <a href="{{i.get_absolute_url}}">{{i.name}}</a></h3>
            <h2 class="price">{{i.price}}</h2>
<!--             -->
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}

app/templates/profil.html
{% extends 'index.html' %}
{%load static%}
{% load crispy_forms_tags %}
{% block main %}

 <div class="content-section">
      <div class="media">

        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
            {% if user.profile.image.url %}
                <img src="{{ user.profile.image.url }}" alt="" class="def">
            {% else %}
                <img src="{% static 'images/default.jpg'%}" alt="" class="def">
            {% endif %}
            <form method="post" class="imgform" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="imgbut">Обновить</button>
  </form>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
     <a href="{% url 'logout' %}">Выйти</a>
    </div>
  </div>
{% endblock %}

app/templates/register.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="main_log">
<div class="signup">

    <div class="reg">
    <form method="POST">
        {% csrf_token %}
        <label aria-hidden="true" id="reg">Регистрация</label>
        <input type="text" id="username" name="username" required placeholder="Имя пользователя">
        <input type="email" id="email" name="email" required placeholder="Почта">
        <input type="password" id="password1" name="password1" required placeholder="Пароль">
        <input type="password" id="password2" name="password2" required placeholder="Повторите пароль ">
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Регистрация</button>
        </div>
    </form>
    </div>

</div>
</div>
{% endblock %}

app/templates/servis.html
{% extends 'index.html' %}

{% block main %}
    <div class="serv">
        <h1>Наш сервис</h1>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2005.2247536895343!2d46.39047253520441!3d55.51077925406221!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x415b20ea60ab9805%3A0x58443b41226f8019!2z0KjRg9C80LXRgNC70LjQvdGB0LrQuNC5INCf0L7Qu9C40YLQtdGF0L3QuNGH0LXRgdC60LjQuSDQotC10YXQvdC40LrRg9C8!5e1!3m2!1sru!2sus!4v1715988553191!5m2!1sru!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
{% endblock %}

app/templates/social.html
{% extends 'index.html' %}
{%load static%}
{% block main %}
      <div class="soc">
          <div class="block">
          <p>Vk</p>
          <a href="https://vk.com/twt2018"><img src="{% static 'images./vk.png'%}" alt=""></a>
              </div>
          <div class="block">
          <p>Discord</p>
          <a href="https://discord.com/accessibility"><img src="{% static 'images./discord.png'%}" alt="" class="disc"></a>
              </div>
          <div class="block">
          <p>Gmail</p>
          <a href="https://discord.com/accessibility"><img src="{% static 'images./gmail.png'%}" alt="" class="disc"></a>
              </div>
          <p>zenas7160@gmail.com</p>
          </div>

          </div>
{% endblock %}

app/templates/vivod_katalog.html
{% extends 'index.html' %}
{% block main %}
<div class="main_vivod">
    {%for i in tovar%}
    <div class="tovars">
        <div class="tv_img">

            <img src="{{i.img.url}}" alt="" class="tovar_img">

        </div>
        <div class="tv_text">
            <h3>{{i.comp}} <a href="{{i.get_absolute_url}}">{{i.name}}</a></h3>
            <h2 class="price">{{i.price}}</h2>
<!--            <a href="#" class="buy">Добавить в корзину</a>-->
        </div>
    </div>
    {%endfor%}
    </div>
{% endblock %}